#!/bin/sh
set -C -e -u

# Tell dh-autoreconf where to search, instead of ./ or -Dsrc/.

# gprofng/libcollector: #1013590 with 2.38.50.20220622-1
# libtoolize: error: AC_CONFIG_MACRO_DIRS([../../config]) conflicts with ACLOCAL_AMFLAGS=-I ..
# Seen with 2.41-4 to 2.43 (autoconf/2.69).

echo src

dirname src/*/configure | grep -v -e gprofng
